version: :3.8

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 11223344
      POSTGRES_DB: ocr_db
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql

  redis:
    image: redis:8.6.3-alpine
    ports:
      - "63797:6379"
